version: '2.4'

services:
  app:
    image: sandrokeil/typescript
    volumes:
      - ./app:/app
    user: ${UID}
    ports:
      - 3000:3000
    environment:
      RESOLVE_SERVER_OPEN_BROWSER: 'false'
    command: yarn dev

  cody:
    image: sandrokeil/typescript
    volumes:
      - ./cody:/app
      - ./app:/dist
    user: ${UID}
    ports:
      - 3322:3000
      - 9229:9229
#    command: npm run debug
    command: npm run watch
